In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import jaccard_score
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from tqdm import tqdm
tqdm.pandas()
from scipy.sparse import csr_matrix
from sklearn.preprocessing import LabelEncoder
from scipy.sparse import coo_matrix

In [2]:
embeddings = pd.read_pickle('../Pickle/review_embeddings.pkl')

In [3]:
embeddings

,index,review_id,embeddings
0,0,46c92eb29261563fd0720195be906055,"[-7.792418e-05, -0.032275986, 0.0055438434, 0...."
1,1,9a5dca4f9760ce1dbccb6f0f1f8ec225,"[0.0543851, -0.0073153717, 0.04655035, 0.06886..."
2,2,8b786d859353bbe353f671cc43ed5333,"[-0.0035193115, 0.041192595, -0.019038284, -0...."
3,3,a0bd075a70a87d3b3914613a14284f19,"[-0.09103633, 0.04891755, 0.04304993, -0.00606..."
4,4,d43ea0a34a0767057b664e8e83e54716,"[-0.004201821, 0.007380954, 0.022725789, -0.07..."
...,...,...,...
499995,499995,a683b2370822b86f77d8be60cf133f60,"[-0.06199075, -0.08846711, 0.057026155, 0.0016..."
499996,499996,aa377ea48f929f353a2b4c7c4161b20f,"[-0.034285337, 0.022729404, 0.08831293, -0.030..."
499997,499997,ac18ac5d3bc96b6b17127bdee3f6da3f,"[-0.012328973, -0.011779773, 0.012324084, 0.00..."
499998,499998,ec53a8468d079a043ba6e84913fc9821,"[-0.06487239, 0.010395286, -0.013465319, 0.022..."
499999,499999,609d97a5ab35079532fbf1446e3c316f,"[-0.03607011, -0.062363364, 0.040098604, 0.051..."

In [4]:
reviews = pd.read_pickle('../Pickle/reviews.pkl')

In [5]:
reviews

,review_id,rating,review_text,n_votes,n_comments,user_id,book_id,cleaned_text,sentiment,confidence,Confidence Score
0,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,16,0,0,14,Mind blowingly cool Best science fiction read ...,1,0.979499,0.979499
1,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,28,1,0,21,special book started slow first third middle t...,1,0.719050,0.719050
2,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,6,0,0,22,read fun mystery book sure ever read Poirot lo...,1,0.991836,0.991836
3,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",22,4,0,23,Fun fast paced disturbing tale murder Great be...,1,0.996752,0.996752
4,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,8,0,0,24,fun book gives sense living Paris expat apprec...,1,0.999605,0.999605
...,...,...,...,...,...,...,...,...,...,...,...
999995,d53ddb7d0ee121a47e8d1ed144f04709,0,I GIVE THIS BOOK: 3 1/2 out of 5 stars \n This...,0,0,26619,34363,GIVE BOOK 3 5 stars book gives lot storyline d...,1,0.696703,0.696703
999996,ecfec5fc89629da466d5c49358e55a33,4,I read a .pdf version of this book that was se...,0,0,26619,125749,read version book sent author giveaway drawing...,1,0.957435,0.957435
999997,6afb14b8dc8e42dbef89964bce8586cc,4,"""Every now and then, you have an encounter wit...",0,0,26619,248053,Every encounter someone simply changes life co...,1,0.998328,0.998328
999998,884fb68ca4e27d3a255d37620fc438e5,0,I GIVE THIS BOOK: 4 1/2 out of 5 stars \n This...,0,0,26619,35425,GIVE BOOK 4 5 stars first official book parano...,1,0.939541,0.939541
999999,5cbc5b0ee190302b70f6360bc1383743,0,This is a very easy and tidy read. Sometimes I...,0,0,26619,387204,easy tidy read Sometimes wonder grew different...,0,0.985717,0.014283